---
title: "bayes_ASD"
author: "Victor Møller"
date: "5 mar 2019"
output: html_document
---

```{r setup, include=FALSE}

library(pacman)
p_load(rethinking, tidyverse)
d <- read.csv("Assignment3Data.csv")

```


```{r cars}

#Filtering visit 1 & neurotypicals 
d1 <- d %>%
  filter(Visit == 1) %>%
  filter(ASD == 1)


#Centering (JanCo style)

colname <- c("VerbalIQ", "NonVerbalIQ", "SocialIQ")

mutate_func <- function(var) {
  return( (var - mean(var) ) / sd(var) )
}

d2 <- d1 %>%
  mutate_at(vars(colname), mutate_func)

d2$ADOS <- d2$ADOS - mean(d2$ADOS)
```

Predictive prior checks. 
non-verbal IQ only (so far)

```{r pressure, echo=FALSE}

#predictive prior check manual
mu <- rnorm(10000, 0, 15)
sigma <- abs(rnorm(10000, 0, 5)) #mu with rnorm. 
y <- rnorm(10000, mu, sigma)
dens(y) 

#predictive prior check with BRMS (Riccardo style)
library(brms)
m1 <- bf(NonVerbalIQ ~ 1 + ADOS)
get_prior(m1, d2, family = gaussian) 

#prior predictive check - Riccardo style 
prior = c(prior(normal(0, 10), class = "Intercept"), prior(normal(0.5, 2), class = "b"), prior(normal(0,10), class = "sigma"))

m0_prior <- brm(m1, family = gaussian, d2, prior = prior, sample_prior = "only", chain = 1, iter = 500)  

pp_check(m0_prior) #looks but quite variable & outside of the real dist. 

m0_prior <- brm(m1, family = gaussian, d2, prior = prior, sample_prior = TRUE, chain = 1, iter = 500)

pp_check(m0_prior) #not too bad. 

```

Model (book style).
Maybe we should also fit the model with brms?

```{r}
#making model (getting help from glimmer)
glimmer(NonVerbalIQ ~ 1 + ADOS, d2)

#model 1
m1 <- rethinking::map(
alist(
NonVerbalIQ ~ dnorm(mu, sigma),
mu <- Intercept + b_ADOS*ADOS,
Intercept ~ dnorm(0, 10),
b_ADOS ~ dnorm(.5, 2),
sigma ~ dnorm(0, 10)
),
data = d2)
precis(m1) #for every b_ADOS --> -.66 IQ 

summary(d2$ADOS)
ADOS.seq <- seq( from=-14 , to=8 , by=1 )
sim.ADOS <- sim(m1, data = list(ADOS = ADOS.seq))
IQ.PI <- apply( sim.ADOS , 2 , PI , prob=0.89)

mu <- link(m1)
mu <- link( m1 , data=data.frame(ADOS=ADOS.seq) )
mu.mean <- apply( mu , 2 , mean )
mu.HPDI <- apply( mu , 2 , HPDI , prob=0.89 )

plot(NonVerbalIQ ~ ADOS , d2 , col=col.alpha(rangi2,1))
lines(ADOS.seq , mu.mean) #issue here. 
# draw HPDI region for line
shade( mu.HPDI , ADOS.seq )
# draw PI region for simulated heights
shade( IQ.PI , ADOS.seq ) 

```

